In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

NumPy Task1 :
Create a 1D array of numbers from 0 to 9

In [28]:
array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

NumPy Task2 :
Create a 3×3 NumPy array of all Boolean value Trues

In [29]:
array_2 = np.ones(9, dtype=bool).reshape(3,3)
array_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

NumPy Task3 :
Extract all odd numbers from array of 1-10

In [14]:
odd_numbers = np.arange(1,11,2)
odd_numbers

array([1, 3, 5, 7, 9])

NumPy Task4 :
Replace all odd numbers in an array of 1-10 with the value -1

In [26]:
my_array = np.arange(1,11)
my_array[::2]= -1
my_array

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

NumPy Task5 :
Convert a 1D array to a 2D array with 2 rows

In [27]:
array_4 = np.arange(1,21).reshape(2,-1)
array_4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

NumPy Task6 :
Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals
